name: Run DataDog Synthetics Tests

on: [push, pull_request]

jobs:
  run-synthetics-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run DataDog Synthetics Tests
        uses: DataDog/synthetics-ci-github-action@87b505388a22005bb8013481e3f73a367b9a53eb
        with:
          api_key: ${{ 32def7c2-b68c-480e-91b3-9bd781ccb280 }}
          app_key: ${{ 5958c771a68834f29ae075472d5fdbb2 }}